const FACupWinners = [
    { team: "Arsenal", wins: "13", last: "2017" },
    { team: "Manchester United", wins: "12", last: "2016" },
    { team: "Chelsea", wins: "8", last: "2018" },
    { team: "Tottenham Hotspur", wins: "8", last: "1991" },
    { team: "Liverpool", wins: "7", last: "2006" },
    { team: "Aston Villa", wins: "7", last: "1957" },
    { team: "Newcastle United", wins: "6", last: "1955" },
    { team: "Manchester City", wins: "6", last: "2019" },
    { team: "Blackburn Rovers", wins: "6", last: "1928" },
    { team: "Everton", wins: "5", last: "1995" },
    { team: "West Bromwich Albion", wins: "5", last: "1968" },
    { team: "Wanderers", wins: "5", last: "1878" },
    { team: "Wolverhampton Wanderers", wins: "4", last: "1960" },
    { team: "Bolton Wanderers", wins: "4", last: "1958" },
    { team: "Sheffield United", wins: "4", last: "1925" },
    { team: "Sheffield Wednesday", wins: "3", last: "1935" },
    { team: "West Ham United", wins: "3", last: "1980" },
    { team: "Preston North End", wins: "2", last: "1938" },
    { team: "Old Etonians", wins: "2", last: "1882" },
    { team: "Portsmouth", wins: "2", last: "2008" },
    { team: "Sunderland", wins: "2", last: "1973" },
    { team: "Nottingham Forest", wins: "2", last: "1959" },
    { team: "Bury", wins: "2", last: "1903" },
    { team: "Huddersfield Town", wins: "1", last: "1922" },
    { team: "Oxford University", wins: "1", last: "1874" },
    { team: "Royal Engineers", wins: "1", last: "1875" },
    { team: "Derby County", wins: "1", last: "1946" },
    { team: "Leeds United", wins: "1", last: "1972" },
    { team: "Southampton", wins: "1", last: "1976" },
    { team: "Burnley", wins: "1", last: "1914" },
    { team: "Cardiff City", wins: "1", last: "1927" },
    { team: "Blackpool", wins: "1", last: "1953" },
    { team: "Clapham Rovers", wins: "1", last: "1880" },
    { team: "Notts County", wins: "1", last: "1894" },
    { team: "Barnsley", wins: "1", last: "1912" },
    { team: "Charlton Athletic", wins: "1", last: "1947" },
    { team: "Old Carthusians", wins: "1", last: "1881" },
    { team: "Blackburn Olympic", wins: "1", last: "1883" },
    { team: "Bradford City", wins: "1", last: "1911" },
    { team: "Ipswich Town", wins: "1", last: "1978" },
    { team: "Coventry City", wins: "1", last: "1987" },
    { team: "Wimbledon", wins: "1", last: "1988" },
    { team: "Wigan Athletic", wins: "1", last: "2013" },
]

export default FACupWinners;